import { CiMedicalCross } from "react-icons/ci";
import { RiMentalHealthLine } from "react-icons/ri";
import { LiaHospitalAltSolid } from "react-icons/lia";
import { LiaIdCardAltSolid } from "react-icons/lia";
import { GiMedicines } from "react-icons/gi";
import { GiMedicalDrip } from "react-icons/gi";

export const doctors = [
    {
        id: 1,
        name: 'Dr. Smith',
        specialty: 'Cardiology',
        location: 'Taipei',
        phone: '555-1234',
        email: 'dr.smith@example.com',
        availability: 'Mon, Wed, Fri',
        url: "https://images.pexels.com/photos/6129437/pexels-photo-6129437.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 2,
        name: 'Dr. Johnson',
        specialty: 'Dermatology',
        location: 'Paris',
        phone: '555-5678',
        email: 'dr.johnson@example.com',
        availability: 'Tue, Thu, Sat',
        url: "https://images.pexels.com/photos/8460157/pexels-photo-8460157.jpeg",
    },
    {
        id: 3,
        name: 'Dr. White',
        specialty: 'Ophthalmology',
        location: 'Madrid',
        phone: '555-9876',
        email: 'dr.white@example.com',
        availability: 'Mon, Fri',
        url: "https://images.pexels.com/photos/6749778/pexels-photo-6749778.jpeg",
    },
    {
        id: 4,
        name: 'Dr. Collins',
        specialty: 'Ophthalmology',
        location: 'Berlin',
        phone: '555-9876',
        email: 'dr.collins@example.com',
        availability: 'Mon, Fri',
        url: "https://images.pexels.com/photos/7447008/pexels-photo-7447008.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 5,
        name: 'Dr. Anderson',
        specialty: 'Ophthalmology',
        location: 'New York',
        phone: '555-9876',
        email: 'dr.anderson@example.com',
        availability: 'Mon, Fri',
        url: "https://images.pexels.com/photos/5207104/pexels-photo-5207104.jpeg",
    },
    {
        id: 6,
        name: 'Dr. Martinez',
        specialty: 'Neurology',
        location: '303 Cedar St, Riverside',
        phone: '555-6543',
        email: 'dr.martinez@example.com',
        availability: 'Mon, Wed, Fri',
        url: "https://images.pexels.com/photos/4989135/pexels-photo-4989135.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 7,
        name: 'Dr. Taylor',
        specialty: 'Gynecology',
        location: '404 Elm St, Lakeside',
        phone: '555-2345',
        email: 'dr.taylor@example.com',
        availability: 'Thu, Sat, Sun',
        url: "https://images.pexels.com/photos/7904486/pexels-photo-7904486.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 8,
        name: 'Dr. Myriah',
        specialty: 'ENT (Ear, Nose, Throat)',
        location: '505 Walnut St, Hilltop',
        phone: '555-7654',
        email: 'dr.white@example.com',
        availability: 'Tue, Thu, Sun',
        url: "https://images.pexels.com/photos/8413397/pexels-photo-8413397.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 9,
        name: 'Dr. Anna Monroe',
        specialty: 'Internal Medicine',
        location: '606 Poplar St, Mountainside',
        phone: '555-8765',
        email: 'dr.davis@example.com',
        availability: 'Mon, Wed, Sat',
        url: "https://images.pexels.com/photos/8442283/pexels-photo-8442283.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 10,
        name: 'Dr. Lee Yun',
        specialty: 'Psychiatry',
        location: '707 Spruce St, Valleyview',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Wed, Fri, Sun',
        url: "https://images.pexels.com/photos/15962796/pexels-photo-15962796/free-photo-of-doctor-in-scrubs-and-a-stethoscope-around-her-neck.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 11,
        name: 'Dr. Rodriguez',
        specialty: 'Cardiology',
        location: '808 Cedar St, Beachtown',
        phone: '555-1111',
        email: 'dr.rodriguez@example.com',
        availability: 'Tue, Thu, Sat',
        url: "https://images.pexels.com/photos/12495583/pexels-photo-12495583.jpeg",
    },
    {
        id: 12,
        name: 'Dr. Walker',
        specialty: 'Orthopedics',
        location: '909 Pine St, Hillside',
        phone: '555-2222',
        email: 'dr.walker@example.com',
        availability: 'Mon, Wed, Fri',
        url: "https://images.pexels.com/photos/7966284/pexels-photo-7966284.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 13,
        name: 'Dr. Turner',
        specialty: 'Pediatrics',
        location: '101 Maple St, Lakeside',
        phone: '555-3333',
        email: 'dr.turner@example.com',
        availability: 'Thu, Sat, Sun',
        url: "https://images.pexels.com/photos/5327580/pexels-photo-5327580.jpeg",
    },
    {
        id: 14,
        name: 'Dr. Anna Monroe',
        specialty: 'Internal Medicine',
        location: '606 Poplar St, Mountainside',
        phone: '555-8765',
        email: 'dr.davis@example.com',
        availability: 'Mon, Wed, Sat',
        url: "https://images.pexels.com/photos/8442283/pexels-photo-8442283.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 15,
        name: 'Dr. Lee Yun',
        specialty: 'Psychiatry',
        location: '707 Spruce St, Valleyview',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Wed, Fri, Sun',
        url: "https://images.pexels.com/photos/15962796/pexels-photo-15962796/free-photo-of-doctor-in-scrubs-and-a-stethoscope-around-her-neck.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 16,
        name: 'Dr. Oliver',
        specialty: 'Neurologist',
        location: 'Tainan',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Tue, Wed, Thu',
        url: "https://images.pexels.com/photos/4167541/pexels-photo-4167541.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 17,
        name: 'Dr. Adam',
        specialty: 'Rheumatologist',
        location: 'Taipei',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Tue, Sat, Sun',
        url: "https://images.pexels.com/photos/5452268/pexels-photo-5452268.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 18,
        name: 'Dr. Justin',
        specialty: 'Oncologist',
        location: 'New Taipei',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Tue, Thu, Sun',
        url: "https://images.pexels.com/photos/17993619/pexels-photo-17993619/free-photo-of-doctor-with-stethoscope-and-tablet.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 19,
        name: 'Dr. Selena',
        specialty: 'Orthopedist',
        location: 'Taoyuan',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Tue, Thu, Sat',
        url: "https://images.pexels.com/photos/5998474/pexels-photo-5998474.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 20,
        name: 'Dr. Tucker',
        specialty: 'Endocrinologist',
        location: 'Taoyuan',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Mon, Tue, Sun',
        url: "https://images.pexels.com/photos/8460157/pexels-photo-8460157.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 21,
        name: 'Dr. James',
        specialty: 'Radiologist',
        location: 'Taichung',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Wed, Thu, Fri',
        url: "https://images.pexels.com/photos/12660379/pexels-photo-12660379.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 22,
        name: 'Dr. Thompson',
        specialty: 'Nephrologist',
        location: 'Taichung',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Mon, Tue, Sat',
        url: "https://images.pexels.com/photos/10691259/pexels-photo-10691259.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 23,
        name: 'Dr. Isabella',
        specialty: 'Anesthesiologist',
        location: 'Kaohsiung',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Thu, Fri, Sat',
        url: "https://images.pexels.com/photos/6749773/pexels-photo-6749773.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 24,
        name: 'Dr. Reynolds',
        specialty: 'Hematopathologist',
        location: 'Keelung',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Mon, Wed, Thu',
        url: "https://images.pexels.com/photos/6129500/pexels-photo-6129500.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 25,
        name: 'Dr. Parker',
        specialty: 'Immunologist',
        location: 'Hsinchu',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Mon, Tue, Wed',
        url: "https://images.pexels.com/photos/14438788/pexels-photo-14438788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 26,
        name: 'Dr. Tony',
        specialty: 'Dermatologist',
        location: 'Miaoli',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Fri, Sat, Sun',
        url: "https://images.pexels.com/photos/6129500/pexels-photo-6129500.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 27,
        name: 'Dr. Carter',
        specialty: 'Endocrinologist',
        location: 'Changhua',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Wed, Thu, Fri',
        url: "https://images.pexels.com/photos/5998474/pexels-photo-5998474.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 28,
        name: 'Dr. Mitchell',
        specialty: 'Pulmonologist',
        location: 'Nantou',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Mon, Tue, Sat',
        url: "https://images.pexels.com/photos/15962796/pexels-photo-15962796/free-photo-of-doctor-in-scrubs-and-a-stethoscope-around-her-neck.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 29,
        name: 'Dr. Ava',
        specialty: 'Urologist',
        location: 'Yunlin',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Wed, Thu, Sun',
        url: "https://images.pexels.com/photos/5206931/pexels-photo-5206931.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 30,
        name: 'Dr. Walker',
        specialty: 'Gynecologist',
        location: 'Chiayi',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Mon, Sat, Sun',
        url: "https://img.freepik.com/free-photo/smiling-asian-male-doctor-pointing-upwards_1262-18321.jpg?w=2000&t=st=1703528068~exp=1703528668~hmac=bee5321c7061b6f92d81630c724881f56fed457b1211fee0144dd85261c6c309",
    },
    {
        id: 31,
        name: 'Dr. Lily',
        specialty: 'Cardiologist',
        location: 'Pingtung',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Mon, Tue, Wed',
        url: "https://images.pexels.com/photos/6605090/pexels-photo-6605090.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    {
        id: 32,
        name: 'Dr. Turner',
        specialty: ' Gastroenterologist',
        location: 'Yilan',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Wed, Thu, Sat',
        url: "https://img.freepik.com/free-photo/portrait-health-worker-with-copy-space_23-2148980761.jpg?w=2000&t=st=1703528104~exp=1703528704~hmac=d30c32b29b6f94e3b527a2cb7b4687629945d81843c132b956018cda10377763",
    },
    {
        id: 33,
        name: 'Dr. Harrison',
        specialty: 'Dentist',
        location: 'Hualien',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Thu, Fri, Sun',
        url: "https://img.freepik.com/free-photo/hospital-healthcare-workers-covid-19-treatment-concept-young-doctor-scrubs-making-daily-errands-clinic-listening-patient-symptoms-look-camera-professional-physician-curing-diseases_1258-57233.jpg?w=2000&t=st=1703528122~exp=1703528722~hmac=ae53f0a62f79708afb96d53f7cbc4c179ab798ef2096613151e43e72da58f760",
    },
    {
        id: 34,
        name: 'Dr. Ethan',
        specialty: 'Nephrologist',
        location: 'Zhongli',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Mon, Wed, Thu',
        url: "https://img.freepik.com/free-photo/doctors-day-handsome-brunette-cute-guy-medical-gown-with-crossed-hands_140725-162942.jpg?w=2000&t=st=1703528139~exp=1703528739~hmac=3e373d99574f8782d2ee45266ccc51dba254e908eed7c52794c3bcc907542db9",
    },
    {
        id: 35,
        name: 'Dr. Logan',
        specialty: 'Hematopathologist',
        location: 'Penghu',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Tue, Wed, Thu',
        url: "https://img.freepik.com/premium-photo/asian-doctor-smiling-isolated-white_127345-46.jpg?w=1380",
    },
    {
        id: 36,
        name: 'Dr. Paul',
        specialty: 'Oncologist',
        location: 'Kinmen',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Mon, Sat, Sun',
        url: "https://img.freepik.com/free-photo/cheerful-male-doctor-white-gown-portrait_53876-105121.jpg?w=2000&t=st=1703528193~exp=1703528793~hmac=9e2f8171bc6c75db2a0a080b5465cd36d18edbc2fc025ad1e40a9cb1b120f311",
    },
    {
        id: 37,
        name: 'Dr. Barnett',
        specialty: 'Dermatologist',
        location: 'Lienchiang',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Fri, Sat, Sun',
        url: "https://img.freepik.com/free-photo/cheerful-male-doctor-white-gown-portrait_53876-105121.jpg?w=2000&t=st=1703528193~exp=1703528793~hmac=9e2f8171bc6c75db2a0a080b5465cd36d18edbc2fc025ad1e40a9cb1b120f311",
    },
    {
        id: 38,
        name: 'Dr. Caldwell',
        specialty: 'Dentist',
        location: 'Taoyuan',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Mon, Sat, Sun',
        url: "https://img.freepik.com/premium-photo/glad-confident-attractive-adult-japanese-doctor-white-coat-glasses-with-stethoscope-look-camera_116547-28770.jpg?w=2000",
    },
    {
        id: 39,
        name: 'Dr. Harper',
        specialty: 'Endocrinologist',
        location: 'Taoyuan',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Wed, Thu, Sun',
        url: "https://img.freepik.com/premium-photo/glad-confident-attractive-adult-japanese-doctor-white-coat-glasses-with-stethoscope-look-camera_116547-28770.jpg?w=2000",
    },
    {
        id: 40,
        name: 'Dr. Scarlett',
        specialty: 'Hematologist',
        location: 'Taipei',
        phone: '555-3210',
        email: 'dr.moore@example.com',
        availability: 'Tue, Wed, Thu',
        url: "https://images.pexels.com/photos/15641080/pexels-photo-15641080/free-photo-of-photo-of-a-smiling-young-woman-in-a-medical-apron.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    
];

export const statistics = [
    {
        title: "Patients treated",
        quantity: 3500,
    },
    {
        title: "Available Specialists",
        quantity: 45,
    },
    {
        title: "Years in Market",
        quantity: 13,
    },
    {
        title: "Prizes awarded",
        quantity: 27,
    },

];

export const services = [
    {
        title: "Diagnosis",
        text: "The service provides immediate medical care for acute illnesses or injuries.",
        icon: <CiMedicalCross />,
    },
    {
        title: "Cardiology Services",
        text: "Emergency care available for all patients with critical medical conditions.",
        icon: <GiMedicalDrip />
    },
    {
        title: "Eye Care",
        text: "Urgent medical attention for severe injuries and eye related illnesses.",
        icon: <GiMedicines />,
    },
    {
        title: "Medical Insurance",
        text: "Immediate care for patients with life-threatening physical conditions.",
        icon: <LiaIdCardAltSolid />
    },
    {
        title: "Surgery",
        text: "Rapid medical surgery available response for acute health issues.",
        icon: <LiaHospitalAltSolid />
    },
    {
        title: "Mental Health",
        text: "We also provide mental health assistance for people facing mental issues.",
        icon: <RiMentalHealthLine />,
    }
];



